typography_spectrum: 0.49092
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 1
  lightness: 0.9182661697268486
  saturation: 0.4326307054143399
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: PabloCarmona
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: TEST
    id: eddd7815-6408-401f-aaf7-97c7526c9158
    type: content
favicon: null
title: Pablo Carmona
purpose: []
