name: PabloCarmona
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49092
title: Pablo Carmona
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 1
  lightness: 0.9182661697268486
  saturation: 0.4326307054143399
  rhythmicContrast: 0.5
purpose: []
